.catalog:
  name: "Elasticsearch"
  version: "2.3.4"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 80
      required: true
    - variable: "plugins"
      label: "ElasticSearch Plugins"
      description: "Comma separated list of plugins to install in ElasticSearch"
      type: "string"
      default: "mobz/elasticsearch-head,cloud-aws,delete-by-query"
      required: true
    - variable: "master_heap_size"
      label: "Master Node Heap Size"
      description: "The amount of heap to make available to the master nodes."
      type: "string"
      default: "1G"
      required: true
    - variable: "data_heap_size"
      label: "Data Node Heap Size"
      description: "The amount of heap to make available to the data nodes."
      type: "string"
      default: "30G"
      required: true
    - variable: "client_heap_size"
      label: "Client Heap Size"
      description: "The amount of heap to make available to the client nodes."
      type: "string"
      default: "1G"
      required: true
elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
        index.query.bool.max_clause_count: "4096"
        script.inline: "on"
        script.indexed: "on"
elasticsearch-datanodes:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
        index.query.bool.max_clause_count: "4096"
        script.inline: "on"
        script.indexed: "on"
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "false"
        network.host: "_site_"
        index.query.bool.max_clause_count: "4096"
        script.inline: "on"
        script.indexed: "on"
