.catalog:
  name: "Elasticsearch"
  version: "2.3.4"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 80
      required: true
elasticsearch-masters:
  metadata:
    elasticsearch:
      plugins:
        - delete-by-query
        - mobz/elasticsearch-head
        - cloud-aws
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
        index.query.bool.max_clause_count: "4096"
        script.inline: "on"
        script.indexed: "on"
elasticsearch-datanodes:
  metadata:
    elasticsearch:
      plugins:
        - delete-by-query
        - mobz/elasticsearch-head
        - cloud-aws
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
        index.query.bool.max_clause_count: "4096"
        script.inline: "on"
        script.indexed: "on"
elasticsearch-clients:
  metadata:
    elasticsearch:
      plugins:
        - delete-by-query
        - mobz/elasticsearch-head
        - cloud-aws
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "false"
        network.host: "_site_"
        index.query.bool.max_clause_count: "4096"
        script.inline: "on"
        script.indexed: "on"
